-- MySQL Script generated by MySQL Workbench
-- Fri May 21 12:11:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PesistasBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PesistasBD` ;

-- -----------------------------------------------------
-- Schema PesistasBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PesistasBD` DEFAULT CHARACTER SET utf8 ;
USE `PesistasBD` ;

-- -----------------------------------------------------
-- Table `PesistasBD`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `dni` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `nomina` DOUBLE NULL,
  `cuentabancaria` INT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) ,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC));


-- -----------------------------------------------------
-- Table `PesistasBD`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Productos` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precioventa` DOUBLE NOT NULL,
  `preciocompra` DOUBLE NULL,
  `Stock` INT NOT NULL,
  `Imagen` TEXT NULL,
  `DetallesDelProducto` TEXT NULL,
  `tipoProducto` VARCHAR(45) NOT NULL,
  `precioOferta` DOUBLE NOT NULL,
  `porcentajeDescuento` DOUBLE NOT NULL,
  PRIMARY KEY (`idProductos`),
  UNIQUE INDEX `idProductos_UNIQUE` (`idProductos` ASC));


-- -----------------------------------------------------
-- Table `PesistasBD`.`Carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Carrito` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Carrito` (
  `precioTotalCarrito` DOUBLE NOT NULL,
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCarrito`));


-- -----------------------------------------------------
-- Table `PesistasBD`.`Tarjeta Bancaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Tarjeta Bancaria` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Tarjeta Bancaria` (
  `idTarjeta Bancaria` INT NOT NULL AUTO_INCREMENT,
  `Tarjeta Bancaria` VARCHAR(16) NOT NULL,
  `CVV` VARCHAR(3) NOT NULL,
  `fechacaducidad` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nameOwner` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTarjeta Bancaria`, `Usuario_idUsuario`),
  UNIQUE INDEX `idTarjeta Bancaria_UNIQUE` (`idTarjeta Bancaria` ASC),
  INDEX `fk_Tarjeta Bancaria_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Tarjeta Bancaria_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `PesistasBD`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PesistasBD`.`Envios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Envios` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Envios` (
  `idEnvio` INT NOT NULL AUTO_INCREMENT,
  `Carrito_idCarrito` INT NOT NULL,
  `Tarjeta Bancaria_idTarjeta Bancaria` INT NOT NULL,
  `codigoPostal` VARCHAR(5) NOT NULL,
  `provincia` VARCHAR(20) NOT NULL,
  `localidad` VARCHAR(20) NOT NULL,
  `direccionEnvio` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Envioscol` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEnvio`, `Usuario_idUsuario`),
  UNIQUE INDEX `idEnvio_UNIQUE` (`idEnvio` ASC),
  INDEX `fk_Envios_Carrito1_idx` (`Carrito_idCarrito` ASC),
  INDEX `fk_Envios_Tarjeta Bancaria1_idx` (`Tarjeta Bancaria_idTarjeta Bancaria` ASC),
  INDEX `fk_Envios_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Envios_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `PesistasBD`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_Tarjeta Bancaria1`
    FOREIGN KEY (`Tarjeta Bancaria_idTarjeta Bancaria`)
    REFERENCES `PesistasBD`.`Tarjeta Bancaria` (`idTarjeta Bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `PesistasBD`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PesistasBD`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Categoria_idCategoria` INT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `PesistasBD`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PesistasBD`.`Categoria_has_Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Categoria_has_Productos` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Categoria_has_Productos` (
  `Categoria_idCategoria` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  INDEX `fk_Categoria_has_Productos_Productos1_idx` (`Productos_idProductos` ASC),
  INDEX `fk_Categoria_has_Productos_Categoria1_idx` (`Categoria_idCategoria` ASC),
  PRIMARY KEY (`Categoria_idCategoria`, `Productos_idProductos`),
  CONSTRAINT `fk_Categoria_has_Productos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `PesistasBD`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `PesistasBD`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PesistasBD`.`Imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Imagen` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Imagen` (
  `idImagen` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idImagen`),
  INDEX `fk_Imagen_Productos1_idx` (`Productos_idProductos` ASC),
  UNIQUE INDEX `idImagen_UNIQUE` (`idImagen` ASC),
  CONSTRAINT `fk_Imagen_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `PesistasBD`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PesistasBD`.`Valoracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Valoracion` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Valoracion` (
  `idValoracion` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NULL,
  `valoracion` TINYINT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idValoracion`, `Usuario_idUsuario`),
  INDEX `fk_Valoracion_Productos1_idx` (`Productos_idProductos` ASC),
  UNIQUE INDEX `idValoracion_UNIQUE` (`idValoracion` ASC),
  INDEX `fk_Valoracion_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Valoracion_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `PesistasBD`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Valoracion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `PesistasBD`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PesistasBD`.`Carrito_has_Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PesistasBD`.`Carrito_has_Productos` ;

CREATE TABLE IF NOT EXISTS `PesistasBD`.`Carrito_has_Productos` (
  `Productos_idProductos` INT NOT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `precioTotalCarrito` INT NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  PRIMARY KEY (`Productos_idProductos`, `Carrito_idCarrito`),
  INDEX `fk_Productos_has_Carrito_Carrito1_idx` (`Carrito_idCarrito` ASC),
  INDEX `fk_Productos_has_Carrito_Productos1_idx` (`Productos_idProductos` ASC),
  CONSTRAINT `fk_Productos_has_Carrito_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `PesistasBD`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Carrito_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `PesistasBD`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
