-- MySQL Script generated by MySQL Workbench
-- Sat May 15 19:58:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MATERIAL DEPORTIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MATERIAL DEPORTIVO` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tienda` (
  `idTienda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `posicionGPSX` FLOAT NULL,
  `posicionYGPS` FLOAT NULL,
  PRIMARY KEY (`idTienda`),
  UNIQUE INDEX `idTienda_UNIQUE` (`idTienda` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `dni` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Tienda1_idx` (`Tienda_idTienda` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administradores` (
  `nomina` DOUBLE NOT NULL,
  `cuentabacaria` VARCHAR(24) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`),
  UNIQUE INDEX `Usuario_idUsuario_UNIQUE` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Administradores_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `Usuario_idUsuario1` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario1`),
  UNIQUE INDEX `Usuario_idUsuario1_UNIQUE` (`Usuario_idUsuario1` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precioventa` DOUBLE NOT NULL,
  `preciocompra` DOUBLE NULL,
  `Stock` INT NOT NULL,
  `Imagen` TEXT NULL,
  `DetallesDelProducto` TEXT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `fk_Productos_Tienda1_idx` (`Tienda_idTienda` ASC) VISIBLE,
  UNIQUE INDEX `idProductos_UNIQUE` (`idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `precioTotalCarrito` DOUBLE NOT NULL,
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `Clientes_Usuario_idUsuario1` INT NOT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `fk_Carrito_Clientes1_idx` (`Clientes_Usuario_idUsuario1` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_Clientes1`
    FOREIGN KEY (`Clientes_Usuario_idUsuario1`)
    REFERENCES `mydb`.`Clientes` (`Usuario_idUsuario1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion envio` (
  `idDireccion envio` INT NOT NULL,
  `codigo postal` VARCHAR(5) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `direccionEnvio` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Clientes_Usuario_idUsuario1` INT NOT NULL,
  PRIMARY KEY (`idDireccion envio`),
  INDEX `fk_Direccion envio_Clientes1_idx` (`Clientes_Usuario_idUsuario1` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion envio_Clientes1`
    FOREIGN KEY (`Clientes_Usuario_idUsuario1`)
    REFERENCES `mydb`.`Clientes` (`Usuario_idUsuario1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarjeta Bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarjeta Bancaria` (
  `idTarjeta Bancaria` INT NOT NULL AUTO_INCREMENT,
  `Tarjeta Bancaria` VARCHAR(16) NOT NULL,
  `CVV` VARCHAR(3) NOT NULL,
  `fechacaducidad` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nameOwner` VARCHAR(45) NOT NULL,
  `Clientes_Usuario_idUsuario1` INT NOT NULL,
  PRIMARY KEY (`idTarjeta Bancaria`),
  INDEX `fk_Tarjeta Bancaria_Clientes1_idx` (`Clientes_Usuario_idUsuario1` ASC) VISIBLE,
  UNIQUE INDEX `idTarjeta Bancaria_UNIQUE` (`idTarjeta Bancaria` ASC) VISIBLE,
  CONSTRAINT `fk_Tarjeta Bancaria_Clientes1`
    FOREIGN KEY (`Clientes_Usuario_idUsuario1`)
    REFERENCES `mydb`.`Clientes` (`Usuario_idUsuario1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Envios` (
  `idEnvio` INT NOT NULL AUTO_INCREMENT,
  `Carrito_idCarrito` INT NOT NULL,
  `Direccion envio_idDireccion envio` INT NOT NULL,
  `Clientes_Usuario_idUsuario1` INT NOT NULL,
  `Tarjeta Bancaria_idTarjeta Bancaria` INT NOT NULL,
  PRIMARY KEY (`idEnvio`),
  UNIQUE INDEX `idEnvio_UNIQUE` (`idEnvio` ASC) VISIBLE,
  INDEX `fk_Envios_Carrito1_idx` (`Carrito_idCarrito` ASC) VISIBLE,
  INDEX `fk_Envios_Direccion envio1_idx` (`Direccion envio_idDireccion envio` ASC) VISIBLE,
  INDEX `fk_Envios_Clientes1_idx` (`Clientes_Usuario_idUsuario1` ASC) VISIBLE,
  INDEX `fk_Envios_Tarjeta Bancaria1_idx` (`Tarjeta Bancaria_idTarjeta Bancaria` ASC) VISIBLE,
  CONSTRAINT `fk_Envios_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `mydb`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_Direccion envio1`
    FOREIGN KEY (`Direccion envio_idDireccion envio`)
    REFERENCES `mydb`.`Direccion envio` (`idDireccion envio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_Clientes1`
    FOREIGN KEY (`Clientes_Usuario_idUsuario1`)
    REFERENCES `mydb`.`Clientes` (`Usuario_idUsuario1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envios_Tarjeta Bancaria1`
    FOREIGN KEY (`Tarjeta Bancaria_idTarjeta Bancaria`)
    REFERENCES `mydb`.`Tarjeta Bancaria` (`idTarjeta Bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Categoria_idCategoria` INT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Categoria_Tienda1_idx` (`Tienda_idTienda` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_has_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_has_Productos` (
  `Categoria_idCategoria` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  INDEX `fk_Categoria_has_Productos_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_Categoria_has_Productos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  PRIMARY KEY (`Categoria_idCategoria`, `Productos_idProductos`),
  CONSTRAINT `fk_Categoria_has_Productos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imagen` (
  `idImagen` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idImagen`),
  INDEX `fk_Imagen_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  UNIQUE INDEX `idImagen_UNIQUE` (`idImagen` ASC) VISIBLE,
  CONSTRAINT `fk_Imagen_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Valoracion` (
  `idValoracion` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NULL,
  `valoracion` TINYINT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Clientes_Usuario_idUsuario1` INT NOT NULL,
  PRIMARY KEY (`idValoracion`),
  INDEX `fk_Valoracion_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_Valoracion_Clientes1_idx` (`Clientes_Usuario_idUsuario1` ASC) VISIBLE,
  UNIQUE INDEX `idValoracion_UNIQUE` (`idValoracion` ASC) VISIBLE,
  CONSTRAINT `fk_Valoracion_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Valoracion_Clientes1`
    FOREIGN KEY (`Clientes_Usuario_idUsuario1`)
    REFERENCES `mydb`.`Clientes` (`Usuario_idUsuario1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoOfertado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoOfertado` (
  `Productos_idProductos` INT NOT NULL,
  `preciooferta` DOUBLE NOT NULL,
  `porcentajedescuento` DOUBLE NULL,
  PRIMARY KEY (`Productos_idProductos`),
  UNIQUE INDEX `Productos_idProductos_UNIQUE` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_ProductoOfertado_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos_has_Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos_has_Carrito` (
  `Productos_idProductos` INT NOT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `precioTotalCarrito` INT NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  PRIMARY KEY (`Productos_idProductos`, `Carrito_idCarrito`),
  INDEX `fk_Productos_has_Carrito_Carrito1_idx` (`Carrito_idCarrito` ASC) VISIBLE,
  INDEX `fk_Productos_has_Carrito_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Carrito_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Carrito_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `mydb`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
